accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('register/', views.SignUp.as_view(), name='register'),
]   

courses/urls.py
from django.urls import path, re_path
from . import views

app_name = 'courses'

urlpatterns = [
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create_view'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit_view'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete_view'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(),name='module_content_create'), # content create
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(),name='module_content_update'),# content update
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'), # content delete
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),


    # Displaying
    path('',views.CourseListView.as_view(), name='course_list_view'),
    path('subject/<slug:subject>/', views.CourseListView.as_view(), name='course_subject_list_view'),
    path('<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail_view')

]


students/urls.py
from django.urls import path
from . import views


app_name = 'students_profile'

urlpatterns = [
    path('',views.StudentListProfileView.as_view(), name='student_profile_list'),
    path('profile/create/', views.register, name='student_profile_create'),
    path('profile/upload/', views.upload_student, name='student_profile_upload'),
    path('<int:pk>/profile/', views.StudentDetailProfileView.as_view(), name='student_profile_detail'),
    path('<int:pk>/update/', views.StudentUpdateProfileView.as_view(), name='student_profile_edit'),
    path('<int:pk>/profile/delete/', views.StudentDeleteProfileView.as_view(), name='student_profile_delete'),
    # Student Course Urls
    path('courses/', views.StudentCourseList.as_view(), name='student_course_list'),
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/<pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail_view'),
    path('courses/<pk>/<module_id>/', views.StudentCourseDetailView.as_view(), name='student_course_module_detail_view')
]









courses/models.py
from django.db import models
from django.template.loader import render_to_string
from django.contrib.auth import get_user_model
from teachers.models import TeacherProfile

from .fields import OrderField

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


from students.models import StudentProfile
# Create your models here.


User = get_user_model()


class Subject(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True, blank=True, null=True, help_text='Subject Code')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title 

class Course(models.Model):
    owner = models.ForeignKey(TeacherProfile,on_delete=models.CASCADE, related_name='courses_created')
    title = models.CharField(max_length=300)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='courses')
    slug = models.SlugField(unique=True, blank=True, null=True, help_text='Course Code')
    students = models.ManyToManyField(StudentProfile, related_name='courses_joined', blank=True)
    overview= models.TextField(blank=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    

    class Meta:
        default_permissions = ('add', 'change', 'delete')
        permissions = (
            ('can_enroll','Enroll In Course'),
        )


    def __str__(self):
        return "{} created by {}".format(self.title, self.owner)



class Module(models.Model):
    course = models.ForeignKey(Course, related_name='modules', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return '{}. {}'.format(self.order, self.title)

    class Meta:
        ordering = ['order']

class Content(models.Model):
    module = models.ForeignKey(Module, related_name = 'contents', on_delete=models.CASCADE,limit_choices_to={
        'model__in':(
            'text',
            'video',
            'image',
            'file'
        )
    })
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']
        
class ItemBase(models.Model):
    owner = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE, related_name = '%(class)s_related')
    title = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        abstract = True
    
    def __str__(self):
        return self.title

    def render(self):
        return render_to_string('course/content/{}.html'.format(self._meta.model_name), {'item':self})

class Text(ItemBase):
    content = models.TextField()
class File(ItemBase):
    file = models.FileField(upload_to='courses/file/%Y/%m/%d')
class Image(ItemBase):
    file = models.FileField(upload_to='courses/images/%Y/%m/%d')
class Video(ItemBase):
    url = models.URLField()

courses/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Course, Module



ModuleFormset = inlineformset_factory(
    Course,
    Module, 
    fields = ['title', 'description'],
    extra = 2,
    can_delete = True
)


courses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateResponseMixin, View
from .forms import ModuleFormset
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView,
   
)
from django.views.generic.detail import DetailView
from .models import (
    Course,
    Module,
    Content,
    Subject
)

from django.db.models import Count
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from teachers.models import TeacherProfile
from students.forms import CourseEnrollForm


from django.forms.models import modelform_factory
from django.apps import apps
from django.core.cache import cache
# Create your views here.


# Course
class OwnerMixin(object):
    def get_queryset(self):
        '''
        Generic Mixin
        Queries the the courses by the creator{TeacherProfile} 
        '''
        qs = super(OwnerMixin, self).get_queryset()
        user = TeacherProfile.objects.get(user=self.request.user)
        return qs.filter(owner=user)


class OwnerEditMixin(object):
    '''
    Owner Edit Mixin
        - Will be inherited by the Create and Update view
        - sets the form instance to the the logged in user
    '''
    def form_valid(self, form):
        form.instance.owner = TeacherProfile.objects.get(user=self.request.user)
        return super(OwnerEditMixin, self).form_valid(form)



class OwnerCourseMixin(OwnerMixin):
    model = Course


class OwnerCourseEditMixin(OwnerCourseMixin, OwnerEditMixin):
    template_name = 'course/manage/course/form.html'
    fields = ['title', 'slug','subject','overview']
    success_url = reverse_lazy('courses:manage_course_list')

# List Course According To The Creator Of The Course
class ManageCourseListView(LoginRequiredMixin,OwnerCourseMixin,ListView):
    template_name = 'course/manage/course/list.html'
    login_url = '/'
    


class CourseCreateView(PermissionRequiredMixin,OwnerCourseEditMixin,CreateView):
    permission_required = 'courses.add_course'


class CourseUpdateView(PermissionRequiredMixin,OwnerCourseEditMixin,UpdateView):
    permission_required = 'courses.change_course'


class CourseDeleteView(PermissionRequiredMixin,OwnerCourseMixin, DeleteView):
    success_url = reverse_lazy('courses:manage_course_list')
    template_name = 'course/manage/course/delete.html'
    permission_required = 'courses.delete_course'



#Displaying Course
class CourseListView(TemplateResponseMixin, View):
    model = Course
    template_name = 'course/courses/list.html'


    def get(self, request,subject=None):
        # subjects = Subject.objects.annotate(
        #     total_courses = Count('courses')
        # )
        subjects = cache.get('all_subjects')
        if not subjects:
            subjects = Subject.objects.annotate(
                total_courses = Count('courses')
            )
        cache.set('all_subjects', subjects)
        courses = Course.objects.annotate(
            total_modules=Count('modules')
        )

        if subject:
            subject = get_object_or_404(Subject, slug=subject)
            courses = courses.filter(subject=subject)

        return self.render_to_response({
            'subjects':subjects,
            'subject':subject,
            'courses':courses
        })
        

class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/courses/detail.html'

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        context['enroll_form'] = CourseEnrollForm(initial={'course':self.object})
        return context

# Module

class CourseModuleUpdateView(TemplateResponseMixin, View):
    template_name = 'course/manage/module/formset.html'
    course = None


    def get_formset(self, data=None):
        return ModuleFormset(instance=self.course, data=data)
    
    def dispatch(self, request, pk):
        self.course = get_object_or_404(Course, id=pk, owner= TeacherProfile.objects.get(user=self.request.user))
        return super(CourseModuleUpdateView, self).dispatch(request, pk)
    
    def get(self,request,*args,**kwargs):
        formset = self.get_formset()
        return self.render_to_response({
            'course':self.course,
            'formset':formset
        })
    
    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('courses:manage_course_list')
        return self.render_to_response({
            'course':self.course,
            'formset':formset
        })



# Content


class ContentCreateUpdateView(TemplateResponseMixin, View):
    module = None
    model = None
    obj = None
    template_name = 'course/manage/content/form.html'

    def get_model(self, model_name):
        if model_name in ['text', 'video', 'file', 'image']:
            return apps.get_model(app_label='courses', model_name=model_name)
        return None
    
    def get_form(self, model, *args, **kwargs):
        Form = modelform_factory(model,exclude =[
            'owner',
            'order',
            'date_created',
            'date_updated'
        ])
        return Form(*args, **kwargs)
    
    def dispatch(self,request, module_id, model_name, id=None):
        self.module = get_object_or_404(Module, id=module_id, course__owner=TeacherProfile.objects.get(user=request.user))
        self.model = self.get_model(model_name)
        if id:
            self.obj = get_object_or_404(self.model, id=id, owner=TeacherProfile.objects.get(user=request.user))
        return super(ContentCreateUpdateView,self).dispatch(request, module_id, model_name, id)
    
    def get(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({
            'form':form,
            'object':self.obj
        })
    

    def post(self, request, module_id,model_name, id=None):
        form = self.get_form(self.model, instance=self.obj, data=request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = TeacherProfile.objects.get(user=request.user)
            obj.save()
            if not id:
                Content.objects.create(module=self.module, item=obj)
            return redirect('courses:module_content_list', self.module.id)
        
        return self.render_to_response({
            'form':form,
            'object':object
        })

class ContentDeleteView(View):
    
    def post(self, request, id):
        content = get_object_or_404(Content, id=id,module__course__owner=TeacherProfile.objects.get(user=self.request.user))
        module = content.module
        content.item.delete()
        content.delete()
        return redirect('courses:module_content_list', module.id)
    


class ModuleContentListView(TemplateResponseMixin, View):
    template_name = 'course/manage/module/content_list.html'


    def get(self,request,module_id):
        module = get_object_or_404(Module,id=module_id,course__owner=TeacherProfile.objects.get(user=self.request.user))
        return self.render_to_response({
            'module':module
        })

courses/templates/course/courses/detail.html
{% extends 'base.html' %}
{% block title %} {{ block.super }} | Course | {{ object.title }} {% endblock %}

{% block content %}
<div class="main-content-inner">
    <div class="row">
        <div class="col-lg-9 col-ml-12">
            <div class="row">
                <div class="col-12 mt-5">
                        {% with subject=course.subject %}
                        <h1>{{ object.title }}</h1>
                        <hr />
                        <div class="module">
                            <p>
                                <a href="{% url 'courses:course_subject_list_view' subject.slug%}">{{ subjects.title }}</a>
                                {{ course.modules.count }} module{{course.moudules.count|pluralize}} <br>
                            </p>
                            <p>
                                
                            Instructor : <span class="bold">{{ course.owner }}</span>
                            </p>
                            <p>
                                Date Created : <span class="bold">{{ course.date_created }}</span>   
                            </p>
                            <p>
                                 Updated <span class="bold">{{ course.date_updated|timesince }} ago</span> 
                            </p>

                            <h3 class="mt-2 pt-3">Course Overview</h3>

                            <div class="description mt-2 mb-3">
                            {{ object.overview|linebreaks }}
                            </div>
                            <!-- {% if request.user.is_authenticated %}
                                {% if request.user.studentprofile %}
                                <form action="{% url 'students_profile:student_enroll_course' %}">
                                    {{ enroll_form }}
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-primary" value="Enroll now">
                                </form>
                                {% endif %}
                            {% else %}
                                <a href="{% url 'account:register' %}"></a>
                                <a href="{% url 'students_profile:student_proile_create' %}">Create Student Profile</a>
                            {% endif %} -->
                        </div>
                        {% endwith %}
                </div>  
            </div>
        </div>
    </div>
</div>
{% endblock %}

courses/templates/course/courses/list.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        {% if subject %}
            {{ subject.title }} courses
        {% else %}
            All Courses
        {% endif %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="assets/images/icon/favicon.ico">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/metisMenu.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.min.css' %}">
    <!-- amchart css -->
    <!-- <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" /> -->
    <!-- others css -->
    <link rel="stylesheet" href="{% static 'assets/css/typography.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/default-css.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <!-- modernizr css -->
    <script src="{% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
{% block navbar %}

{% endblock %}


    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- page container area start -->
    <div class="page-container">
        <!-- SIDEBAR -->
        <!-- sidebar menu area start -->
        <div class="sidebar-menu">
            <div class="sidebar-header">
                <div class="logo">
                    <a href="{% url 'dashboard'%}" style="color:white; font-size:23px;">Course Management System</a>                        
                </div>
            </div>
            <div class="main-menu">
                <div class="menu-inner">
                    <nav>
                        <ul class="metismenu" id="menu">
                            <li class="active">
                                <a href="javascript:void(0)" aria-expanded="true"><i class="ti-dashboard"></i><span>dashboard</span></a>
                                <ul class="collapse">
                                    <li><a href="{% url 'dashboard'%}">Dashboard</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-book"></i><span>Courses</span></a>
                                <ul class="collapse">
                                    <!-- <li><a href="{% url 'accordion'%}">All Courses</a></li> -->
                                        
                                        <li {% if not subject %} class="selected" {% endif %}>
                                                <a href="{% url 'courses:course_list_view' %}">All Courses</a>
                                            </li>
                                        <li><a href="{% url 'accordion'%}">Enroll Course</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-book"></i><span>Subjects</span></a>
                                <ul class="collapse">
                                    <!-- <li><a href="{% url 'accordion'%}">All Courses</a></li> -->
                                        
                                    {% for s in subjects %}
                                    <li {% if subject == s %} class = 'selected' {% endif %}>
                                        <a href="{% url 'courses:course_subject_list_view' s.slug%}">{{ s.title }}
                                            <br><span>{{ s.total_courses }} courses</span>
                                        </a>
                                    </li>
                                {% endfor %}
                                </ul>
                            </li>
                                
                            <li>
                            <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-check-square"></i><span>Grades</span></a>
                            <ul class="collapse">
                                <!-- <li><a href="{% url 'accordion'%}">All Courses</a></li> -->
                                    
                                    <!-- <li {% if not subject %} class="selected" {% endif %}>
                                            <a href="{% url 'courses:course_list_view' %}">All Courses</a>
                                        </li>
                                    <li><a href="{% url 'accordion'%}">Enroll Course</a></li> -->
                                    </ul>
                                </li>
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-calendar"></i><span>Timetable</span></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
{% block content %}
<div class="main-content-inner">
    <!-- Course List -->
    <div class="row">
        <!-- basic modal start -->

        {% for course in courses %}
        {% with subject=course.subject %}
        <div class="col-lg-6 mt-5">
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title"><a href="{% url 'courses:course_detail_view'  course.slug%}">{{ course.title }}</a></h4>
                        <p>
                                <a href="{% url 'courses:course_subject_list_view' subject.slug%}">{{ subject }}</a>
                                {{ course.total_modules }} module{{ course.total_modules|pluralize }}.
                                Instructor: {{ course.owner }}            
                        </p>
                    </div>
                </div>
         </div>
         {% endwith %}
         {% endfor %}
    </div>

</div>
{% endblock %}
</div>
    <!-- jquery latest version -->
    <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <!-- bootstrap 4 js -->
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/metisMenu.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- start chart js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <!-- start highcharts js -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <!-- start zingchart js -->
    <script src="https://cdn.zingchart.com/zingchart.min.js"></script>
    <script>
    zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";
    ZC.LICENSE = ["569d52cefae586f634c54f86dc99e6a9", "ee6b7db5b51705a13dc2339db3edaf6d"];
    </script>
    <!-- all line chart activation -->
    <script src="{% static 'assets/js/line-chart.js' %}"></script>
    <!-- all pie chart -->
    <script src="{%static 'assets/js/pie-chart.js' %}"></script>
    <!-- others plugins -->
    <script src="{% static 'assets/js/plugins.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script></body>
</html>
