accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('register/', views.SignUp.as_view(), name='register'),
]   

courses/urls.py
from django.urls import path, re_path
from . import views

app_name = 'courses'

urlpatterns = [
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create_view'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit_view'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete_view'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(),name='module_content_create'), # content create
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(),name='module_content_update'),# content update
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'), # content delete
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),


    # Displaying
    path('',views.CourseListView.as_view(), name='course_list_view'),
    path('subject/<slug:subject>/', views.CourseListView.as_view(), name='course_subject_list_view'),
    path('<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail_view')

]


students/urls.py
from django.urls import path
from . import views


app_name = 'students_profile'

urlpatterns = [
    path('',views.StudentListProfileView.as_view(), name='student_profile_list'),
    path('profile/create/', views.register, name='student_profile_create'),
    path('profile/upload/', views.upload_student, name='student_profile_upload'),
    path('<int:pk>/profile/', views.StudentDetailProfileView.as_view(), name='student_profile_detail'),
    path('<int:pk>/update/', views.StudentUpdateProfileView.as_view(), name='student_profile_edit'),
    path('<int:pk>/profile/delete/', views.StudentDeleteProfileView.as_view(), name='student_profile_delete'),
    # Student Course Urls
    path('courses/', views.StudentCourseList.as_view(), name='student_course_list'),
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/<pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail_view'),
    path('courses/<pk>/<module_id>/', views.StudentCourseDetailView.as_view(), name='student_course_module_detail_view')
]









templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}SMS.ng{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="assets/images/icon/favicon.ico">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/metisMenu.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.min.css' %}">
    <!-- amchart css -->
    <!-- <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" /> -->
    <!-- others css -->
    <link rel="stylesheet" href="{% static 'assets/css/typography.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/default-css.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <!-- modernizr css -->
    <script src="{% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
{% block navbar %}

{% endblock %}


    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- page container area start -->
    <div class="page-container">
        <!-- SIDEBAR -->
        <!-- sidebar menu area start -->
        <div class="sidebar-menu">
            <div class="sidebar-header">
                <div class="logo">
                    <a href="{% url 'dashboard'%}" style="color:white; font-size:23px;">SkillSync</a>                        
                </div>
            </div>
            <div class="main-menu">
                <div class="menu-inner">
                    <nav>
                        <ul class="metismenu" id="menu">
                            <li class="active">
                                <a href="javascript:void(0)" aria-expanded="true"><i class="ti-dashboard"></i><span>dashboard</span></a>
                                <ul class="collapse">
                                    <li><a href="{% url 'dashboard'%}">Dashboard</a></li>
                                </ul>
                            </li>
                            {% if request.user.student or request.user.staff %}
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-book"></i><span>Courses</span></a>
                                <ul class="collapse">
                                    <!-- <li><a href="{% url 'accordion'%}">All Courses</a></li> -->
                                    {% if request.user.staff  or request.user.admin %}  
                                        <li><a href="{% url 'courses:course_create_view'%}">Add Course</a></li>
                                        <li><a href="{% url 'courses:manage_course_list'%}">Your Courses</a></li>
                                        
                                    {% endif %}
                                    {% if request.user.student %}
                                        <li><a href="{% url 'accordion'%}">Enroll Course</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                            {% endif %}
                            <!-- <li>
                                    <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-book"></i><span>Subjects</span></a>
                                    <ul class="collapse">
                                        <li><a href="{% url 'accordion'%}">All Subjects</a></li>                                            
                                        <li><a href="{% url 'accordion'%}">Add Subject</a></li>
                                    </ul>
                                </li>     -->
                             {% if request.user.admin %}   
                            <li>
                                    <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-graduation-cap"></i><span>Staff</span></a>
                                    <ul class="collapse">
                                        <li><a href="{% url 'teacher_profile:teacher_profile_list' %}"><i class="fa fa-users"></i> All Staff</a></li>                                            
                                        <li><a href="{% url 'teacher_profile:teacher_profile_create'%}"><i class="fa fa-user-plus"></i> Add Staff</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                            {% if request.user.admin %}
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-graduation-cap"></i><span>Students</span></a>
                                <ul class="collapse">
                                    <li><a href="{% url 'students_profile:student_profile_list'%}"><i class="fa fa-users"></i> All Students</a></li>                                            
                                    <li><a href="{% url 'students_profile:student_profile_create'%}"><i class="fa fa-user-plus"></i> Add Student</a></li>
                                </ul>
                            </li>
                            {% endif %}
                            {% if request.user.admin %}
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-calendar"></i><span>Generate Timetable</span></a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!-- sidebar menu area end -->
{% block content %}
{% endblock %}
    <!-- offset area end -->
    <!-- jquery latest version -->
    <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <!-- bootstrap 4 js -->
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/metisMenu.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- start chart js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <!-- start highcharts js -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <!-- start zingchart js -->
    <script src="https://cdn.zingchart.com/zingchart.min.js"></script>
    <!-- <script>
    zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";
    ZC.LICENSE = ["569d52cefae586f634c54f86dc99e6a9", "ee6b7db5b51705a13dc2339db3edaf6d"];
    </script> -->
    <!-- all line chart activation -->
    <script src="{% static 'assets/js/line-chart.js' %}"></script>
    <!-- all pie chart -->
    <script src="{%static 'assets/js/pie-chart.js' %}"></script>
    <!-- others plugins -->
    <script src="{% static 'assets/js/plugins.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script></body>
</html>



templates/home.html
{% extends 'base.html' %}
    {% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">

{% block navbar %}
  <header>
    <a href="#" class="nav-trigger"><span></span></a>
  </header>
  <div class="side-nav">
    <nav>
        <ul>
            <li>
                <a href="{% if request.user.teacherprofile %}{{ request.user.teacherprofile.get_absolute_url }} {% else %} {{ request.user.studentprofile.get_absolute_url }} {% endif %}">
                    <span><i class="fas fa-user"></i></span>
                    Profile
                </a>
            </li>
  
            <li>
                <a href="
                {% if request.user.studentprofile %}
                    {% url 'students_profile:student_course_list' %}
                {% elif request.user.teacherprofile %}
                    {% url 'courses:manage_course_list'%}
                {% else %}
                    #
                {% endif %}
                ">
                    <span><i class="fas fa-envelope"></i></span>
                    Courses
                </a>
            </li>

            <li>
                <a href="{% url 'account:logout' %}">
                    <span><i class="fas fa-facebook"></i></span>
                    Logout
                </a>
            </li>
            {% if request.user.is_admin %}
            <li>
              <a href="{% url 'students_profile:student_register'%}">
                  <span><i class="fas fa-facebook"></i></span>
                  Add Students
              </a>
          </li>
          <li>
            <a href="{% url 'teacher_profile:teacher_register'%}">
                <span><i class="fas fa-facebook"></i></span>
                Add Teachers
            </a>
        </li>
        <li>
            <a href="{% url 'account:register'%}">
                <span><i class="fas fa-facebook"></i></span>
                Add Staff
            </a>
        </li>
        <li>
        <a href="#">
            <span><i class="fas fa-facebook"></i></span>
            Create Table
        </a>
        </li>
        
            
        {% endif %}
        </ul>
    </nav>
  </div>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
      <div class="col-md-4">
      </div>
    <div class="col-md-4">
        <div class="user_icon_div">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
            <path class="user_icon" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"/>
        </svg>
        {% if request.user.teacherprofile %}  
        <p>{{ message }} {{ request.user.teacherprofile }}</p>
        {% else %}
        <p>{{ message }} {{ request.user.studentprofile }}</p>
        {% endif %}

        <p>Hello {{ request.user.email }}</p>

    </div>
    </div>
  </div>
</div>
</div>
{% endblock %}